---
experiment_desc: Stripformer_gopro

train:
  files_a: /data1/LJC/New_BDD_100k/frames_avg/100k/train/**/*.png    # blur
  files_b: /ssd1/LJC/New_BDD_100k/frames/100k/train/**/*.png         # sharp
  size: &SIZE 512
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, 1]
  scope: geometric
  filter: True
  fft_hpf: True
  mode: LSTM

val1:
  files_a: /data1/LJC/New_BDD_100k/frames_avg/100k/val/**/*.png
  files_b: /ssd1/LJC/New_BDD_100k/frames/100k/val/**/*.png
  size: *SIZE
  scope: None
  crop: random
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  filter: True
  fft_hpf: True



val2:
  files_a: /data1/LJC/New_BDD_100k/frames_avg/100k/val/**/*.png
  files_b: /ssd1/LJC/New_BDD_100k/frames/100k/val/**/*.png
  size: *SIZE
  scope: None
  crop: random
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  filter: True
  fft_hpf: True



test:
  files_a: /data1/LJC/New_BDD_100k/frames_avg/100k/test/**/*.png
  files_b: /ssd1/LJC/New_BDD_100k/frames/100k/test/**/*.png
  size: *SIZE
  scope: None
  crop: random
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  filter: True
  fft_hpf: True


model:
  g_name: Stripformer_GRU_t
  content_loss: Stripformer_Loss
  mode: LSTM
  best_model_path: gru_t2_best_model

num_epochs: 200
train_batches_per_epoch: 1500
val_batches_per_epoch: 750
test_batches_per_epoch:
batch_size: 2
image_size: [512, 512]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: cosine
  start_epoch: 50
  min_lr: 0.0000001
